### ISSUE TITLE
Healtcheck fails from version 2023-52

### ISSUE THREAD

**Issue by gabimem** [observabilitystack/geoip-api#129]
The health check fails because there is no curl command in the newly generated image, so the process is restarted every so often.

This happens since version 2023-52, apparently since commit 4f316a13476ac5c57304551437774f2c358c269e, where the base image was introduced:

```dockerfile
FROM debian:bookworm-slim
```

and curl has not been installed.

**Comment by tboeghk** [comment]
Thanks @gabimem, I'll take a look! This might be due to the change to a native image in `2023-52`.

**Comment by tboeghk** [comment]
The issue is fixed with the `2023-02` release. Thanks for reporting @gabimem!
