### ISSUE TITLE
missing city/prov information on region IP addresses

### ISSUE THREAD

**Issue by sinawic** [observabilitystack/geoip-api#143]
hi thanks for the great tools you provide

I'm located in Iran and the responses for my IP addresses do not include city info.

> curl -sI -H "X-Geoip-Address: <my public static IP" "http://localhost:8080/"

the response I get:

```
HTTP/1.1 204 
X-Geoip-Country: IR
X-Geoip-Latitude: 35.698
X-Geoip-Longitude: 51.4115
X-Geoip-Continent: AS
X-Geoip-Timezone: Asia/Tehran
X-Geoip-Asn: 42337
X-Geoip-AsnOrganization: Respina Networks & Beyond PJSC
Date: Sat, 27 May 2023 09:52:30 GMT
```

I'm using the docker images:

`observabilitystack/geoip-api:2022-52` and `observabilitystack/geoip-api:2023-21`

I need the city info to be included so I can make dashboards out of it, indicating which cities I get the most requests from
I wanted to know is there any way the data would be included or not!

**Comment by tboeghk** [comment]
Hej @sinawic thanks for raising this issue! 

We're packaging the Maxmind Geoip2 Free Database with the API. It seems that your specific IP information is missing in the free database. You can [check whether your IP is contained in their database using their online service](https://www.maxmind.com/en/geoip-demo). 

If you need a higher resolution for geolocating IPs, you can package the [paid Maxmind database](https://www.maxmind.com/en/solutions/geoip2-enterprise-product-suite/commercial-licensing) along with the API.

**Comment by sinawic** [comment]
hey thanks for the response

Actually I was able to reach my goal of creating a dashboard indicating which cities i get the most requests using elk stack
and bc this container returns "lat" "long" which I didn't notice at first, it's actually a sufficient data for me to do my job.

Thanks for all the work :pray:

**Comment by tboeghk** [comment]
I'll close this issue then!
