### ISSUE TITLE
Add option to set CORS headers

### ISSUE THREAD

**Issue by wug-ge** [observabilitystack/geoip-api#159]
Hi!

thanks for creating this great project!
I'd like to call it directly from my frontend, but I'm getting a CORS error since I deployed it on a different subdomain.

Is there any way to set CORS headers?

Greetings!

**Comment by tboeghk** [comment]
I'll check this!

**Comment by tboeghk** [comment]
I finally found the time. I added CORS headers that by default allow access from all origins. This will be enabled with the next release
