### ISSUE TITLE
Add IPv6 support.

### ISSUE THREAD

**Issue by MartinHotmann** [observabilitystack/geoip-api#68]
Sadly I can not run:

`curl -s http://localhost:8080/2001:db8:3333:4444:5555:6666:7777:8888`

IPv4 is fine, but IPv6 does not work. Since there are some IPv6 exclusive users which are not using any IPv4, they would not be able to be located.

As there are also IPv6 free DBs I would love to see IPv6 beeing supported. Maybe even both should be used:

1. IPv4
2. added missing info from IPv6 (if some from IPv4 are missing, which happens sometimes)

like this:

```
{
    "country":"US",                   #IPv4
    "latitude":"37.751",              #IPv4
    "longitude":"-97.822",            #IPv6 (added to complete, if they would miss)
    "continent":"NA",                 #IPv4
    "timezone":"America/Chicago",     #IPv4
    "asn":15169,                      #IPv6 (added to complete, if they would miss)
    "asnOrganization":"GOOGLE"        #IPv4
}
```

OR

1. IPv4 & IPv6 both outputted like this:

```
ipv4 {
    "country":"US",
    "latitude":"37.751",
    "longitude":"-97.822",
    "continent":"NA",
    "timezone":"America/Chicago",
    "asn":15169,
    "asnOrganization":"GOOGLE"
},
ipv6 {
    "country":"US",
    "latitude":"37.751",
    "longitude":"-97.822",
    "continent":"NA",
    "timezone":"America/Chicago",
    "asn":15169,
    "asnOrganization":"GOOGLE"
}
```

Hope its not too much to ask for. Thanks!

**Comment by tboeghk** [comment]
Hi @MartinHotmann, thanks for your opening this issue.

Under the hood we are using the free MaxMind GeoCity2 database. You can query their raw data using their [online precision demo](https://www.maxmind.com/en/geoip2-precision-demo). 

Using either that demo or the most recent `geoip-api` package for my ip addresses I get proper responses for both my _ipv4_ and _ipv6_ addresses:

```shell
$ curl -s "http://localhost:8080/2A04:4540:653B:2400:3554:67C6:819A:8E1F" | jq         
{
  "country": "DE",
  "stateprov": "Free and Hanseatic City of Hamburg",
  "stateprovCode": "HH",
  "city": "Hamburg",
  "latitude": "53.5844",
  "longitude": "10.0288",
  "continent": "EU",
  "timezone": "Europe/Berlin",
  "asn": 15943,
  "asnOrganization": "wilhelm.tel GmbH"
}
$ curl -s "http://localhost:8080/149.233.220.149" | jq                        
{
  "country": "DE",
  "stateprov": "Free and Hanseatic City of Hamburg",
  "stateprovCode": "HH",
  "city": "Hamburg",
  "latitude": "53.5844",
  "longitude": "10.002",
  "continent": "EU",
  "timezone": "Europe/Berlin",
  "asn": 15943,
  "asnOrganization": "wilhelm.tel GmbH"
}
```

Unfortunately all geoip data results are tied to (and hence limited to) the underlying geoip database. If you want a higher coverage or better precision, you can replace the pre-packages databases with [commercial ones from MaxMind](https://www.maxmind.com/en/geoip2-city).

Given that result I'd like to close this issue as `geoip-api` already has ipv6 support.
