### ISSUE TITLE
[BUG] Formatting not as intended/shown

### ISSUE THREAD

**Issue by MartinHotmann** [observabilitystack/geoip-api#74]
When I run `curl -s http://localhost:8080/8.8.8.8` I get:
```
{"country":"US","latitude":"37.751","longitude":"-97.822","continent":"NA","timezone":"America/Chicago","asn":15169,"asnOrganization":"GOOGLE"}
```

What I would expect is:

```
{
  "country":"US",
  "latitude":"37.751",
  "longitude":"-97.822",
  "continent":"NA",
  "timezone":"America/Chicago",
  "asn":15169,
  "asnOrganization":"GOOGLE"
}
```

It is not formatted. That also shows when I display the output on a browser. It sadly looks not very pleasing and beautiful.

**Comment by tboeghk** [comment]
Hi @MartinHotmann thanks for your issue. The output you get is the raw JSON output printed on the terminal using `curl`. To have is properly formatted (like in the example), you have to pipe the `curl` output through `jq`:

```shell
$ curl -s "http://localhost:8080/$(curl -s https://ifconfig.me/ip)" | jq
{
  "country": "DE",
  "stateprov": "Free and Hanseatic City of Hamburg",
  "stateprovCode": "HH",
  "city": "Hamburg",
  "latitude": "53.5742",
  "longitude": "10.0497",
  "continent": "EU",
  "timezone": "Europe/Berlin",
  "asn": 15943,
  "asnOrganization": "wilhelm.tel GmbH"
}
```

But as this is neither a bug nor related to the functionality of this project, I close this issue.

**Comment by MartinHotmann** [comment]
`jq` is not a default tool on many linux machines therefore I think it should be implemented in the docker container, rather then installed on the machine globaly. I think this is bad practice.

I am aware of `jq` and think it should not get used as I would prefer `json_pp` with these arguments `-json_opt pretty,canonical`:

`$ curl -s "http://localhost:8080/$(curl -s https://ifconfig.me/ip)" | json_pp -json_opt pretty,canonical`

since `json_pp` is a default tool is almost all Unix/Linux based systems, but I was more wondering why it does not come out already formatted? But never mind.
