### ISSUE TITLE
Missing Location Accuracy Radius 

### ISSUE THREAD

**Issue by AndTessitore** [observabilitystack/geoip-api#97]
Would be nice to have accuracy radius info after lat and long.
You can find it in https://maxmind.github.ui/GeoIP2-java:
![image](https://user-images.githubusercontent.com/45067216/163399084-e09c5056-f984-464b-97ea-59f873d49434.png)

**Comment by tboeghk** [comment]
Hi @AndTessitore, thanks for the heads up, I'll check it out!

**Comment by tboeghk** [comment]
The accuracyRadius is available starting from the `2023-01` release.
